spring.application.name=devshop
server.port=8080

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://devops-project-mysql.cja04iwcwh1p.ap-south-1.rds.amazonaws.com:3306/devshop}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sakthi58}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:sh0p~rds}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
