---
- name: Disable swap
  shell: |
    swapoff -a
    sed -i '/ swap / s/^/#/' /etc/fstab
  changed_when: true

- name: Install Kubernetes packages
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    update_cache: true

- name: Hold Kubernetes packages
  shell: apt-mark hold kubelet kubeadm kubectl
  changed_when: false

- name: Enable kubelet
  systemd:
    name: kubelet
    enabled: true
    state: started
